### ISSUE TITLE
`feature`: Create a project website

### ISSUE THREAD

**Issue by gyptazy** [gyptazy/ProxLB#35]
## General
With the attraction of more people into this project it might also be great to have a project website. This task is about creating a website for the project.

## Tasks
- [x] Get a domain (https://proxlb.de)
- [x] Enable DNSSec
- [x] Enable SSL certificate
- [x] Create temporary landing page
- [x] Create real website

**Comment by gyptazy** [comment]
The website is now available at https://proxlb.de
